@startuml
participant Actor
Actor -> Game : run
activate Game
Game -> Game : updateGame
activate Game
Game -> Intro : update
activate Intro
Intro -> Intro : stopMusic
activate Intro
Intro --> Intro
deactivate Intro
Intro -> Game : changeGameState
activate Game
Game -> GameScreen : setPanelSize
activate GameScreen
GameScreen --> Game
deactivate GameScreen
Game --> Intro
deactivate Game
Intro --> Game
deactivate Intro
Game --> Game
deactivate Game
return
@enduml